In [1]:
print("Hello World!")

Hello World!


In [8]:
import numpy as np
my_arr = np.arange(10_000_000)
my_list = list(range(10_000_000))

In [9]:
%timeit my_arr2 = my_arr*2

59.4 ms ± 1.02 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [13]:
%timeit my_list2 = [x*2 for x in my_list]

1.68 s ± 150 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [19]:
data1 = np.array([[1.5,-0.1,3],[0,-3,6.5]])
data1

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [20]:
data1*10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [21]:
data1+data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [15]:
a=np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
a.shape

(3, 4)

In [26]:
np.arange(1,6,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5])

In [35]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [40]:
np.round(np.random.randn(2,2),2)

array([[-1.53, -0.43],
       [ 0.48, -0.45]])

In [42]:
g=np.arange(24)
print(g)
print("Rank:",g.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
Rank: 1


In [43]:
g.shape=(6,4)
print(g)
print("Range:",g.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Range: 2


In [44]:
g.shape=(2,3,4)
print(g)
print("Rank:",g.ndim)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Rank: 3


In [45]:
a = np.array([14,23,32,41])
b = np.array([5,4,3,2])
print("a+b =",a+b)
print("a-b =",a-b)
print("a*b =",a*b)
print("a/b =",a/b)
print("a//b =",a//b)
print("a%b =",a%b)
print("a**b =",a**b)

a+b = [19 27 35 43]
a-b = [ 9 19 29 39]
a*b = [70 92 96 82]
a/b = [ 2.8         5.75       10.66666667 20.5       ]
a//b = [ 2  5 10 20]
a%b = [4 3 2 1]
a**b = [537824 279841  32768   1681]


In [46]:
m=np.array([20,-5,30,40])
m<[15,16,35,36]

array([False,  True,  True, False])

In [47]:
m<25

array([ True,  True, False, False])

In [48]:
m[m<25]

array([20, -5])

In [55]:
a = np.array([[-2.5,3.1,7],[10,11,12]])
print(a)
print("mean =",a.mean(0)) #for row wise we will give 1

[[-2.5  3.1  7. ]
 [10.  11.  12. ]]
mean = [3.75 7.05 9.5 ]


In [60]:
a = np.array([1,5,3,19,13,7,3])
a

array([ 1,  5,  3, 19, 13,  7,  3])

In [65]:
a[2::2]

array([ 3, 13,  3])

In [64]:
a[::-1]

array([  3,   7,  13, 999,   3,   5,   1])

In [63]:
a[3]=999
a

array([  1,   5,   3, 999,  13,   7,   3])

In [66]:
import numpy as np

In [67]:
m1 = np.arange(10).reshape(2,5)
m1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [68]:
m1.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [69]:
m2=np.arange(5)
m2

array([0, 1, 2, 3, 4])

In [72]:
n1=np.arange(10).reshape(2,5)
n1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [73]:
n2=np.arange(15).reshape(5,3)
n2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [74]:
n1.dot(n2)

array([[ 90, 100, 110],
       [240, 275, 310]])

In [75]:
import numpy.linalg as linalg
m3=np.array([[1,2,3],[5,7,11],[21,29,31]])
m3

array([[ 1,  2,  3],
       [ 5,  7, 11],
       [21, 29, 31]])

In [77]:
m3=np.array([[1,2],[3,1]])
m3

array([[1, 2],
       [3, 1]])

In [78]:
linalg.inv(m3)

array([[-0.2,  0.4],
       [ 0.6, -0.2]])

In [79]:
linalg.pinv(m3)

array([[-0.2,  0.4],
       [ 0.6, -0.2]])

In [80]:
m3.dot(linalg.inv(m3))

array([[1., 0.],
       [0., 1.]])

In [81]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
import numpy as np
m3 = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])



In [7]:
eigenvalues,eigenvectors =np.linalg.eig(m3)
eigenvalues

array([ 1.61168440e+01, -1.11684397e+00, -9.75918483e-16])

In [15]:
def get_name():
    name = input("Enter your name: ")
    print(f"Hello, {name}!")
get_name()   

Enter your name:  mithu


Hello, mithu!


In [9]:
def say_hello():
    print("Hello Nithya!")
say_hello()    

Hello Nithya!


In [18]:
def factorial(n):
    fact = 1
    print(f"{n}! = ", end="")

    for i in range(n, 0, -1):
        print(i, end=" × " if i != 1 else "")
        fact *= i

    print(f" = {fact}")



num = int(input("Enter a number: "))
factorial(num)


Enter a number:  5


5! = 5 × 4 × 3 × 2 × 1 = 120


In [29]:
def check_twenty(a, b):
    
    if a == 20 or b == 20:
        return True
    elif a+b==20:
        return True
    else:
        return False


a = int(input("Enter first number: "))
b = int(input("Enter second number: "))

result = check_twenty(a, b)
print("Result:",result)

    

Enter first number:  -3
Enter second number:  -17


Result: False


In [51]:
def old_macdonald(name):
    if len(name) >= 4:
        result = ""
        for i in range(len(name)):
            if i == 0 or i == 5:
                result += name[i].upper()
            else:
                result += name[i]
        return result
    else:
        return name

text=input("Enter a text:")
print(old_macdonald(text))


Enter a text: nithya


NithyA


In [47]:
def old_macdonald(name):
    return name.upper()

text=input("Enter a text:")
print(old_macdonald(text))



Enter a text: nithya


NITHYA


In [48]:
type(a)

int

In [49]:
def change_name(name):
    return name.replace("n", "m")

print(change_name("nithya"))  


mithya
